name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          npm ci -f
          CI=false npm run build --if-present
      - name: removing prev build directory from server
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: mkdir testcicd
          host: 13.127.183.100
          user: ubuntu
          key: ${{ secrets.AWS_MOTOR_PRIVATE }}

      # - name: transfer file using ssh
      #   uses: easingthemes/ssh-deploy@v2
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.AWS_MOTOR_PRIVATE }}
      #     ARGS: "-rltDzvO"
      #     SOURCE: "build"
      #     REMOTE_HOST: 13.127.183.100
      #     REMOTE_USER: ubuntu
      #     TARGET: /home/ubuntu/
      #     EXCLUDE: "README.md, .gitignore, .github"

      # - name: updating directories in the server
      #   uses: fifsky/ssh-action@v0.0.6
      #   with:
      #     command: |
      #       rm -rf frontend_old
      #       mv frontend frontend_old
      #       mv build frontend
      #       mkdir build
      #     host: 13.127.183.100
      #     user: ubuntu
      #     key: ${{ secrets.AWS_MOTOR_PRIVATE }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      


  # Explore-GitHub-Actions:
    # 

    # strategy:
    #   matrix:
    #     node-version: [16.x]
    # steps:
    #   - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    #   - name: List files in the repository
    #     run: |
    #       ls ${{ github.workspace }}
    #   - name: reading the App.jsx file
    #     run: |
    #       cat src/App.jsx
    #   - name: installing and running app
    #     uses: actions/checkout@v3
    #   - run: npm install
    #   - run: npm run build
    #   - uses: actions/checkout@v3
    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #       cache: "npm"
    #   - run: |
    #       npm ci -f
    #       CI=false npm run build --if-present
    #   - name: removing prev build directory from server
    #     uses: fifsky/ssh-action@v0.0.6
    #     with:
    #       command: rm -rf build
    #       host: 13.127.183.100
    #       user: ubuntu
    #       key: ${{ secrets.AWS_MOTOR_PRIVATE }}

    #   - name: transfer file using ssh
    #     uses: easingthemes/ssh-deploy@v2
    #     env:
    #       SSH_PRIVATE_KEY: ${{ secrets.AWS_MOTOR_PRIVATE }}
    #       ARGS: "-rltDzvO"
    #       SOURCE: "build"
    #       REMOTE_HOST: 13.127.183.100
    #       REMOTE_USER: ubuntu
    #       TARGET: /home/ubuntu/
    #       EXCLUDE: "README.md, .gitignore, .github"

    #   - name: updating directories in the server
    #     uses: fifsky/ssh-action@v0.0.6
    #     with:
    #       command: |
    #         rm -rf frontend_old
    #         mv frontend frontend_old
    #         mv build frontend
    #         mkdir build
    #       host: 13.127.183.100
    #       user: ubuntu
    #       key: ${{ secrets.AWS_MOTOR_PRIVATE }}
    #   - run: echo "🍏 This job's status is ${{ job.status }}."
